# Generated by Django 5.0.6 on 2024-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
