# Generated by Django 5.0.6 on 2024-07-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_singer_name_song_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='relese',
            new_name='release',
        ),
    ]
