# Generated by Django 5.0.3 on 2024-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
