# Generated by Django 5.0.3 on 2024-07-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_comment_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='singer',
            name='tag',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
